version: '3.5'
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: users-management
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - database


networks:
   database:
     driver: bridge
